apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-kafka
  template:
    metadata:
      labels:
        app: barista-kafka
    spec:
      containers:
      - name: barista-kafka
        image: barista-kafka
        ports:
          - containerPort: 8090
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1