apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-http
  template:
    metadata:
      labels:
        app: barista-http
    spec:
      containers:
      - name: barista-http
        image: barista-http
        ports:
          - containerPort: 8082
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1